### ISSUE TITLE
ImportError: cannot import name 'OneCycleLR' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by nxnixin** [MaartenGr/PolyFuzz#7]
Hi, really thanks for your amazing library firstly.

I got an error when I run " from polyfuzz import PolyFuzz" and I have installed all of the requirements. I could not run your library due to this error.

> /Users/nixin/anaconda3/bin/python /Users/nixin/PycharmProjects/run.py
Traceback (most recent call last):
  File "/Users/nixin/PycharmProjects/test_similarity/run.py", line 8, in <module>
    from polyfuzz import PolyFuzz
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/polyfuzz/__init__.py", line 1, in <module>
    from .polyfuzz import PolyFuzz
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/polyfuzz/polyfuzz.py", line 7, in <module>
    from polyfuzz.models import TFIDF, RapidFuzz, Embeddings, BaseMatcher
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/polyfuzz/models/__init__.py", line 10, in <module>
    from ._embeddings import Embeddings
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/polyfuzz/models/_embeddings.py", line 8, in <module>
    from flair.embeddings import DocumentPoolEmbeddings, WordEmbeddings, TokenEmbeddings
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/flair/__init__.py", line 22, in <module>
    from . import trainers
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/flair/trainers/__init__.py", line 1, in <module>
    from .trainer import ModelTrainer
  File "/Users/nixin/anaconda3/lib/python3.7/site-packages/flair/trainers/trainer.py", line 33, in <module>
    from torch.optim.lr_scheduler import OneCycleLR
ImportError: cannot import name 'OneCycleLR' from 'torch.optim.lr_scheduler' (/Users/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py)

My PyTorch version is 1.2.0.

Do you know what's the reason caused this? I appreciate any suggestions. Thanks in advance.

**Comment by MaartenGr** [comment]
Can you try it in a fresh conda env? Does the problem then still persist? 

I just tried it out in a fresh google colab session and I am not getting that issue.

**Comment by nxnixin** [comment]
> Can you try it in a fresh conda env? Does the problem then still persist?
> 
> I just tried it out in a fresh google colab session and I am not getting that issue.

I found it works on jupyternotebook.  It seems flair library has an issue on my pycharm env.
It is weird. But thanks anyway. I need to check more.
